# Generated by Django 2.1.5 on 2022-09-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subitulo', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'registros de pruebas',
                'verbose_name_plural': 'pruebas',
            },
        ),
    ]
