# Generated by Django 4.1 on 2022-09-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_options_empleado_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='habilidad')),
            ],
            options={
                'verbose_name': 'Habilidades',
                'verbose_name_plural': 'Habilidadess',
            },
        ),
    ]
