# Generated by Django 4.1 on 2022-09-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_habilidades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilidades',
            new_name='Habilidad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='empleado.habilidad'),
        ),
    ]
