# Generated by Django 4.1 on 2022-09-06 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_alter_habilidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['jobs'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados de la empresa'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='historia',
            field=ckeditor.fields.RichTextField(default='historia por registrar'),
            preserve_default=False,
        ),
    ]
